apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: product
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: product
      previewService: product
      autoPromotionEnabled: true
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
